#!/usr/bin/env zsh

function rainbow() {
  local -a cs
  [[ $# -eq 0 ]] && cs=(fg fg_no_bold fg_bold bg bg_no_bold bg_bold) || cs=($@)
  for c in $cs; do
    echo "$c"
    for k v in ${(Pkv)c}; do
      printf '%s %s -- [%s%s\n' "$v" "$k" "$(tr '[' '\\[' <<<"$v")" "$reset_color"
    done | column -t -s '--'
    echo ""
  done
}
